#Enableing this disabled the normal plugin and is used to generate the config file for newer minecraft versions
#To do so set it to true, put the new items in your inventory and run /additems
entrymode: false
ItemFound 1-20-6: ''
1-20-6:
- WOLF_ARMOR
- ARMADILLO_SCUTE
ItemFound 1-21: ''
1-21:
- TUFF_BRICK_SLAB
- TUFF_BRICK_STAIRS
- TUFF_BRICK_WALL
- TUFF_BRICKS
- TUFF_SLAB
- TUFF_STAIRS
- TUFF_WALL
- WIND_CHARGE
- FLOW_BANNER_PATTERN
- GUSTER_BANNER_PATTERN
- BREEZE_ROD
- CHISELED_TUFF
- CHISELED_TUFF_BRICKS
- CRAFTER
- GUSTER_POTTERY_SHERD
- HEAVY_CORE
- FLOW_POTTERY_SHERD
- OMINOUS_TRIAL_KEY
- MUSIC_DISC_PRECIPICE
- MUSIC_DISC_CREATOR
- MUSIC_DISC_CREATOR_MUSIC_BOX
- OMINOUS_BOTTLE
- MACE
- POLISHED_TUFF
- POLISHED_TUFF_STAIRS
- POLISHED_TUFF_SLAB
- POLISHED_TUFF_WALL
- SCRAPE_POTTERY_SHERD
- FLOW_ARMOR_TRIM_SMITHING_TEMPLATE
- BOLT_ARMOR_TRIM_SMITHING_TEMPLATE
- TRIAL_KEY
- WAXED_CHISELED_COPPER
- WAXED_COPPER_GRATE
- WAXED_COPPER_DOOR
- WAXED_COPPER_TRAPDOOR
- WAXED_COPPER_BULB
- COPPER_TRAPDOOR
- EXPOSED_COPPER_TRAPDOOR
- WEATHERED_COPPER_TRAPDOOR
- OXIDIZED_COPPER_TRAPDOOR
- CHISELED_COPPER
- COPPER_GRATE
- EXPOSED_CHISELED_COPPER
- EXPOSED_COPPER_GRATE
- WEATHERED_CHISELED_COPPER
- WEATHERED_COPPER_GRATE
- OXIDIZED_CHISELED_COPPER
- OXIDIZED_COPPER_GRATE
- COPPER_DOOR
- COPPER_BULB
- EXPOSED_COPPER_DOOR
- EXPOSED_COPPER_BULB
- WEATHERED_COPPER_DOOR
- WEATHERED_COPPER_BULB
- OXIDIZED_COPPER_DOOR
- OXIDIZED_COPPER_BULB
- WAXED_OXIDIZED_CHISELED_COPPER
- WAXED_OXIDIZED_COPPER_GRATE
- WAXED_OXIDIZED_COPPER_DOOR
- WAXED_OXIDIZED_COPPER_TRAPDOOR
- WAXED_OXIDIZED_COPPER_BULB
- WAXED_WEATHERED_CHISELED_COPPER
- WAXED_WEATHERED_COPPER_GRATE
- WAXED_WEATHERED_COPPER_DOOR
- WAXED_WEATHERED_COPPER_TRAPDOOR
- WAXED_WEATHERED_COPPER_BULB
- WAXED_EXPOSED_CHISELED_COPPER
- WAXED_EXPOSED_COPPER_GRATE
- WAXED_EXPOSED_COPPER_DOOR
- WAXED_EXPOSED_COPPER_TRAPDOOR
- WAXED_EXPOSED_COPPER_BULB
