# Enableing this disabled the normal plugin and is used to generate the config file for newer minecraft versions
# To do so set it to true, put the new items in your inventory and run /additems
# values
entrymode: false
# replace dots in version with a dash this only a reference and does not need to be the actual version
mcVersion: 1-21
# data
1-21:
  - MUSIC_DISC_CREATOR_MUSIC_BOX
  - OMINOUS_BOTTLE
  - OMINOUS_TRIAL_KEY
  - SCRAPE_POTTERY_SHERD
  - BOLT_ARMOR_TRIM_SMITHING_TEMPLATE
  - FLOW_ARMOR_TRIM_SMITHING_TEMPLATE
  - TRIAL_KEY
  - WIND_CHARGE
  - CRAFTER
  - FLOW_POTTERY_SHERD
  - GUSTER_POTTERY_SHERD
  - FLOW_BANNER_PATTERN
  - GUSTER_BANNER_PATTERN
  - BREEZE_ROD
  - MACE
  - HEAVY_CORE
  - MUSIC_DISC_PRECIPICE
  - MUSIC_DISC_CREATOR
  - CHISELED_TUFF
  - TUFF_WALL
  - TUFF_SLAB
  - TUFF_STAIRS
  - TUFF_BRICKS
  - TUFF_BRICK_STAIRS
  - TUFF_BRICK_SLAB
  - TUFF_BRICK_WALL
  - CHISELED_TUFF_BRICKS
  - POLISHED_TUFF_WALL
  - POLISHED_TUFF_SLAB
  - POLISHED_TUFF_STAIRS
  - POLISHED_TUFF
  - WEATHERED_CHISELED_COPPER
  - EXPOSED_COPPER_GRATE
  - OXIDIZED_COPPER_DOOR
  - OXIDIZED_CHISELED_COPPER
  - COPPER_GRATE
  - OXIDIZED_COPPER_GRATE
  - COPPER_BULB
  - EXPOSED_COPPER_BULB
  - CHISELED_COPPER
  - EXPOSED_CHISELED_COPPER
  - WEATHERED_COPPER_GRATE
  - COPPER_DOOR
  - EXPOSED_COPPER_TRAPDOOR
  - WEATHERED_COPPER_BULB
  - EXPOSED_COPPER_DOOR
  - WEATHERED_COPPER_DOOR
  - COPPER_TRAPDOOR
  - OXIDIZED_COPPER_TRAPDOOR
  - WEATHERED_COPPER_TRAPDOOR
  - OXIDIZED_COPPER_BULB
  - WAXED_OXIDIZED_CHISELED_COPPER
  - WAXED_COPPER_TRAPDOOR
  - WAXED_EXPOSED_COPPER_TRAPDOOR
  - WAXED_WEATHERED_COPPER_BULB
  - WAXED_EXPOSED_CHISELED_COPPER
  - WAXED_COPPER_GRATE
  - WAXED_WEATHERED_COPPER_GRATE
  - WAXED_OXIDIZED_COPPER_GRATE
  - WAXED_EXPOSED_COPPER_DOOR
  - WAXED_WEATHERED_COPPER_TRAPDOOR
  - WAXED_OXIDIZED_COPPER_TRAPDOOR
  - WAXED_CHISELED_COPPER
  - WAXED_WEATHERED_CHISELED_COPPER
  - WAXED_COPPER_DOOR
  - WAXED_WEATHERED_COPPER_DOOR
  - WAXED_EXPOSED_COPPER_GRATE
  - WAXED_OXIDIZED_COPPER_DOOR
  - WAXED_OXIDIZED_COPPER_BULB
  - WAXED_EXPOSED_COPPER_BULB
  - WAXED_COPPER_BULB