name: firstitemv3
version: '${project.version}'
main: org.asdanjer.firstitemv3.FirstItemV3
api-version: '1.20'
commands:
  additems:
    description: Adds the items to the config file.
    usage: /<command>
    permission: firstitemv3.additems
    default: op